export const MATRIX_DATA = {
  "UNSC (United Nations Security Council)": [
    { country: "Australia", status: "Open" },
    { country: "Brazil", status: "Open" },
    { country: "Canada", status: "Open" },
    { country: "China", status: "Open" },
    { country: "France", status: "Open" },
    { country: "Germany", status: "Open" },
    { country: "Greenland", status: "Open" },
    { country: "India", status: "Open" },
    { country: "Iran", status: "Open" },
    { country: "Israel", status: "Open" },
    { country: "Italy", status: "Open" },
    { country: "Kazakhstan", status: "Open" },
    { country: "Pakistan", status: "Open" },
    { country: "Palestine", status: "Open" },
    { country: "Russia", status: "Open" },
    { country: "Saudi Arabia", status: "Open" },
    { country: "South Africa", status: "Open" },
    { country: "Spain", status: "Open" },
    { country: "Turkey", status: "Open" },
    { country: "UAE", status: "Open" },
    { country: "UK", status: "Open" },
    { country: "Ukraine", status: "Open" },
    { country: "USA", status: "Open" },
    { country: "Venezuela", status: "Open" },
    { country: "Vietnam", status: "Open" }
  ],
  "UNGA (United Nations General Assembly)": [
    { country: "Afghanistan", status: "Open" },
    { country: "Algeria", status: "Open" },
    { country: "Argentina", status: "Open" },
    { country: "Armenia", status: "Open" },
    { country: "Australia", status: "Open" },
    { country: "Azerbaijan", status: "Open" },
    { country: "Bangladesh", status: "Open" },
    { country: "Belarus", status: "Open" },
    { country: "Belgium", status: "Open" },
    { country: "Bolivia", status: "Open" },
    { country: "Brazil", status: "Open" },
    { country: "Canada", status: "Open" },
    { country: "Chile", status: "Open" },
    { country: "China", status: "Open" },
    { country: "Colombia", status: "Open" },
    { country: "Cuba", status: "Open" },
    { country: "Denmark", status: "Open" },
    { country: "Egypt", status: "Open" },
    { country: "Ethiopia", status: "Open" },
    { country: "Finland", status: "Open" },
    { country: "France", status: "Open" },
    { country: "Georgia", status: "Open" },
    { country: "Germany", status: "Open" },
    { country: "India", status: "Open" },
    { country: "Indonesia", status: "Open" },
    { country: "Iran", status: "Open" },
    { country: "Iraq", status: "Open" },
    { country: "Israel", status: "Open" },
    { country: "Italy", status: "Open" },
    { country: "Japan", status: "Open" },
    { country: "Jordan", status: "Open" },
    { country: "Kazakhstan", status: "Open" },
    { country: "Lebanon", status: "Open" },
    { country: "Libya", status: "Open" },
    { country: "Malaysia", status: "Open" },
    { country: "Maldives", status: "Open" },
    { country: "Malta", status: "Open" },
    { country: "Mexico", status: "Open" },
    { country: "Myanmar", status: "Open" },
    { country: "Nepal", status: "Open" },
    { country: "Netherlands", status: "Open" },
    { country: "New Zealand", status: "Open" },
    { country: "Nigeria", status: "Open" },
    { country: "North Korea", status: "Open" },
    { country: "Norway", status: "Open" },
    { country: "Pakistan", status: "Open" },
    { country: "Palestine", status: "Open" },
    { country: "Peru", status: "Open" },
    { country: "Philippines", status: "Open" },
    { country: "Poland", status: "Open" },
    { country: "Qatar", status: "Open" },
    { country: "Russia", status: "Open" },
    { country: "Saudi Arabia", status: "Open" },
    { country: "Singapore", status: "Open" },
    { country: "Somalia", status: "Open" },
    { country: "South Africa", status: "Open" },
    { country: "South Korea", status: "Open" },
    { country: "Spain", status: "Open" },
    { country: "Sri Lanka", status: "Open" },
    { country: "Sudan", status: "Open" },
    { country: "Sweden", status: "Open" },
    { country: "Syria", status: "Open" },
    { country: "Thailand", status: "Open" },
    { country: "Türkiye", status: "Open" },
    { country: "Ukraine", status: "Open" },
    { country: "United Arab Emirates", status: "Open" },
    { country: "United Kingdom", status: "Open" },
    { country: "United States", status: "Open" },
    { country: "Venezuela", status: "Open" },
    { country: "Vietnam", status: "Open" }
  ],
  "AIPPM (All India Political Parties Meet)": [
    { country: "Narendra Modi", status: "Open" },
    { country: "Amit Shah", status: "Open" },
    { country: "Rajnath Singh", status: "Open" },
    { country: "J. P. Nadda", status: "Open" },
    { country: "Nitin Gadkari", status: "Open" },
    { country: "Yogi Adityanath", status: "Open" },
    { country: "Shivraj Singh Chouhan", status: "Open" },
    { country: "Devendra Fadnavis", status: "Open" },
    { country: "Himanta Biswa Sarma", status: "Open" },
    { country: "Smriti Irani", status: "Open" },
    { country: "Piyush Goyal", status: "Open" },
    { country: "Dharmendra Pradhan", status: "Open" },
    { country: "Anurag Thakur", status: "Open" },
    { country: "Nupur Sharma", status: "Open" },
    { country: "Tejasvi Surya", status: "Open" },
    { country: "Suvendu Adhikari", status: "Open" },
    { country: "K. Annamalai", status: "Open" },
    { country: "Sambit Patra", status: "Open" },
    { country: "Nishikant Dubey", status: "Open" },
    { country: "Sudhanshu Trivedi", status: "Open" },
    { country: "Ravi Shankar Prasad", status: "Open" },
    { country: "Kiren Rijiju", status: "Open" },
    { country: "Ashwini Vaishnaw", status: "Open" },
    { country: "Giriraj Singh", status: "Open" },
    { country: "Sonia Gandhi", status: "Occupied" },
    { country: "Rahul Gandhi", status: "Occupied" },
    { country: "Mallikarjun Kharge", status: "Open" },
    { country: "Priyanka Gandhi Vadra", status: "Occupied" },
    { country: "Shashi Tharoor", status: "Occupied" },
    { country: "Jairam Ramesh", status: "Open" },
    { country: "Sachin Pilot", status: "Open" },
    { country: "Bhupesh Baghel", status: "Open" },
    { country: "K. C. Venugopal", status: "Open" },
    { country: "Pawan Khera", status: "Open" },
    { country: "Deepender Hooda", status: "Open" },
    { country: "Gaurav Gogoi", status: "Open" },
    { country: "Randeep Singh Surjewala", status: "Open" },
    { country: "Salman Khurshid", status: "Open" },
    { country: "Arvind Kejriwal", status: "Open" },
    { country: "Atishi Marlena", status: "Open" },
    { country: "Manish Sisodia", status: "Open" },
    { country: "Mamata Banerjee", status: "Open" },
    { country: "Abhishek Banerjee", status: "Open" },
    { country: "Mehbooba Mufti", status: "Open" },
    { country: "Akhilesh Yadav", status: "Open" },
    { country: "Jaya Bachchan", status: "Open" },
    { country: "Tejashwi Yadav", status: "Open" },
    { country: "Manoj Jha", status: "Open" },
    { country: "Thalapathy Vijay", status: "Open" },
    { country: "M. K. Stalin", status: "Open" },
    { country: "Kanimozhi", status: "Open" },
    { country: "D. K. Shivakumar", status: "Open" },
    { country: "K. Chandrashekar Rao", status: "Open" },
    { country: "K. T. Rama Rao", status: "Open" },
    { country: "Chandrababu Naidu", status: "Open" },
    { country: "Priyanka Chaturvedi", status: "Occupied" },
    { country: "Pawan Kalyan", status: "Open" },
    { country: "H. D. Kumaraswamy", status: "Open" },
    { country: "Uddhav Thackeray", status: "Open" },
    { country: "Aaditya Thackeray", status: "Open" },
    { country: "Eknath Shinde", status: "Open" },
    { country: "Sharad Pawar", status: "Open" },
    { country: "Supriya Sule", status: "Open" },
    { country: "Sanjay Raut", status: "Open" },
    { country: "Naveen Patnaik", status: "Open" },
    { country: "Nitish Kumar", status: "Open" },
    { country: "Chirag Paswan", status: "Open" },
    { country: "Hemant Soren", status: "Open" },
    { country: "Omar Abdullah", status: "Open" },
    { country: "Asaduddin Owaisi", status: "Open" }
  ],
  "UNCSW (UN Commission on the Status of Women)": [
    { country: "Afghanistan", status: "Open" },
    { country: "Argentina", status: "Open" },
    { country: "Australia", status: "Open" },
    { country: "Bangladesh", status: "Open" },
    { country: "Belgium", status: "Open" },
    { country: "Brazil", status: "Open" },
    { country: "Canada", status: "Open" },
    { country: "China", status: "Open" },
    { country: "Colombia", status: "Open" },
    { country: "Democratic Republic of Congo", status: "Open" },
    { country: "Egypt", status: "Open" },
    { country: "Finland", status: "Open" },
    { country: "France", status: "Open" },
    { country: "Germany", status: "Open" },
    { country: "Hungary", status: "Open" },
    { country: "India", status: "Open" },
    { country: "Indonesia", status: "Open" },
    { country: "Iran", status: "Open" },
    { country: "Iraq", status: "Open" },
    { country: "Israel", status: "Open" },
    { country: "Italy", status: "Open" },
    { country: "Japan", status: "Open" },
    { country: "Jordan", status: "Open" },
    { country: "Kenya", status: "Open" },
    { country: "Lebanon", status: "Open" },
    { country: "Libya", status: "Open" },
    { country: "Malaysia", status: "Open" },
    { country: "Malta", status: "Open" },
    { country: "Mexico", status: "Open" },
    { country: "Myanmar", status: "Open" },
    { country: "Nepal", status: "Open" },
    { country: "Netherlands", status: "Open" },
    { country: "New Zealand", status: "Open" },
    { country: "Nigeria", status: "Open" },
    { country: "North Korea", status: "Open" },
    { country: "Norway", status: "Open" },
    { country: "Pakistan", status: "Open" },
    { country: "Palestine", status: "Open" },
    { country: "Poland", status: "Open" },
    { country: "Qatar", status: "Open" },
    { country: "Romania", status: "Open" },
    { country: "Russia", status: "Open" },
    { country: "Saudi Arabia", status: "Open" },
    { country: "South Africa", status: "Open" },
    { country: "South Korea", status: "Open" },
    { country: "Spain", status: "Open" },
    { country: "Sri Lanka", status: "Open" },
    { country: "Sudan", status: "Open" },
    { country: "Sweden", status: "Open" },
    { country: "Switzerland", status: "Open" },
    { country: "Syria", status: "Open" },
    { country: "Thailand", status: "Open" },
    { country: "Türkiye", status: "Open" },
    { country: "Uganda", status: "Open" },
    { country: "Ukraine", status: "Open" },
    { country: "United Arab Emirates", status: "Open" },
    { country: "United Kingdom", status: "Open" },
    { country: "United States", status: "Open" },
    { country: "Venezuela", status: "Open" },
    { country: "Yemen", status: "Open" }
  ],
  "UNFCCC (UN Framework Convention on Climate Change)": [
    { country: "Afghanistan", status: "Open" },
    { country: "Argentina", status: "Open" },
    { country: "Australia", status: "Open" },
    { country: "Bangladesh", status: "Open" },
    { country: "Belgium", status: "Open" },
    { country: "Brazil", status: "Open" },
    { country: "Canada", status: "Open" },
    { country: "China", status: "Open" },
    { country: "Colombia", status: "Open" },
    { country: "Democratic Republic of Congo", status: "Open" },
    { country: "Egypt", status: "Open" },
    { country: "Finland", status: "Open" },
    { country: "France", status: "Open" },
    { country: "Germany", status: "Open" },
    { country: "Hungary", status: "Open" },
    { country: "India", status: "Open" },
    { country: "Indonesia", status: "Open" },
    { country: "Iran", status: "Open" },
    { country: "Iraq", status: "Open" },
    { country: "Israel", status: "Open" },
    { country: "Italy", status: "Open" },
    { country: "Japan", status: "Open" },
    { country: "Jordan", status: "Open" },
    { country: "Kenya", status: "Open" },
    { country: "Lebanon", status: "Open" },
    { country: "Libya", status: "Open" },
    { country: "Malaysia", status: "Open" },
    { country: "Malta", status: "Open" },
    { country: "Mexico", status: "Open" },
    { country: "Myanmar", status: "Open" },
    { country: "Nepal", status: "Open" },
    { country: "Netherlands", status: "Open" },
    { country: "New Zealand", status: "Open" },
    { country: "Nigeria", status: "Open" },
    { country: "North Korea", status: "Open" },
    { country: "Norway", status: "Open" },
    { country: "Pakistan", status: "Open" },
    { country: "Palestine", status: "Open" },
    { country: "Poland", status: "Open" },
    { country: "Qatar", status: "Open" },
    { country: "Romania", status: "Open" },
    { country: "Russia", status: "Open" },
    { country: "Saudi Arabia", status: "Open" },
    { country: "South Africa", status: "Open" },
    { country: "South Korea", status: "Open" },
    { country: "Spain", status: "Open" },
    { country: "Sri Lanka", status: "Open" },
    { country: "Sudan", status: "Open" },
    { country: "Sweden", status: "Open" },
    { country: "Switzerland", status: "Open" },
    { country: "Syria", status: "Open" },
    { country: "Thailand", status: "Open" },
    { country: "Türkiye", status: "Open" },
    { country: "Uganda", status: "Open" },
    { country: "Ukraine", status: "Open" },
    { country: "United Arab Emirates", status: "Open" },
    { country: "United Kingdom", status: "Open" },
    { country: "United States", status: "Open" },
    { country: "Venezuela", status: "Open" },
    { country: "Yemen", status: "Open" }
  ],
  "Coachella (Simulated Crisis)": [
    { country: "Amit Trivedi", status: "Open" },
    { country: "Anuv Jain", status: "Open" },
    { country: "AP Dhillon", status: "Open" },
    { country: "A. R. Rahman", status: "Open" },
    { country: "Badshah", status: "Open" },
    { country: "B Praak", status: "Open" },
    { country: "Diljit Dosanjh", status: "Open" },
    { country: "Divine", status: "Open" },
    { country: "Guru Randhawa", status: "Open" },
    { country: "Honey Singh", status: "Open" },
    { country: "Jasmine Sandlas", status: "Open" },
    { country: "Kailash Kher", status: "Open" },
    { country: "Karan Aujla", status: "Open" },
    { country: "King", status: "Open" },
    { country: "Krsna", status: "Open" },
    { country: "Masoom Sharma", status: "Open" },
    { country: "Neha Kakkar", status: "Open" },
    { country: "Parmish Verma", status: "Open" },
    { country: "Prateek Kuhad", status: "Open" },
    { country: "Pritam", status: "Open" },
    { country: "Raftaar", status: "Open" },
    { country: "Seedhe Maut", status: "Open" },
    { country: "Satinder Sartaaj", status: "Open" },
    { country: "Shashwat Singh", status: "Open" },
    { country: "Shreya Ghoshal", status: "Open" },
    { country: "Sidhu Moosewala", status: "Open" },
    { country: "Sonu Nigam", status: "Open" },
    { country: "Sunidhi Chauhan", status: "Open" },
    { country: "Vishal Mishra", status: "Open" }
  ],
  "IPL (Indian Premier League)": [
    { country: "Chennai Super Kings (CSK)", status: "Open" },
    { country: "Delhi Capitals (DC)", status: "Open" },
    { country: "Gujarat Titans (GT)", status: "Open" },
    { country: "Kolkata Knight Riders (KKR)", status: "Open" },
    { country: "Lucknow Super Giants (LSG)", status: "Open" },
    { country: "Mumbai Indians (MI)", status: "Open" },
    { country: "Punjab Kings (PBKS)", status: "Open" },
    { country: "Rajasthan Royals (RR)", status: "Open" },
    { country: "Royal Challengers Bengaluru (RCB)", status: "Open" },
    { country: "Sunrisers Hyderabad (SRH)", status: "Open" }
  ],
  "International Press": [
    { country: "Journalist 1", status: "Open" },
    { country: "Journalist 2", status: "Open" },
    { country: "Journalist 3", status: "Open" },
    { country: "Journalist 4", status: "Open" },
    { country: "Journalist 5", status: "Open" },
    { country: "Journalist 6", status: "Open" },
    { country: "Journalist 7", status: "Open" },
    { country: "Journalist 8", status: "Open" },
    { country: "Journalist 9", status: "Open" },
    { country: "Journalist 10", status: "Open" },
    { country: "Photographer 1", status: "Open" },
    { country: "Photographer 2", status: "Open" },
    { country: "Photographer 3", status: "Open" },
    { country: "Photographer 4", status: "Open" },
    { country: "Photographer 5", status: "Open" },
    { country: "Photographer 6", status: "Open" },
    { country: "Photographer 7", status: "Open" },
    { country: "Photographer 8", status: "Open" },
    { country: "Photographer 9", status: "Open" },
    { country: "Photographer 10", status: "Open" },
    { country: "Caricaturist 1", status: "Open" },
    { country: "Caricaturist 2", status: "Open" },
    { country: "Caricaturist 3", status: "Open" },
    { country: "Caricaturist 4", status: "Open" },
    { country: "Caricaturist 5", status: "Open" },
    { country: "Caricaturist 6", status: "Open" },
    { country: "Caricaturist 7", status: "Open" },
    { country: "Caricaturist 8", status: "Open" },
    { country: "Caricaturist 9", status: "Open" },
    { country: "Caricaturist 10", status: "Open" }
  ]
};
